Revert addition to onNewIntent function
Revert addition to onNewIntent function from v3.11.0 to avoid Error on Build with Gradle v7.0: 

> Task :react-native-nfc-manager:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
/react-native-nfc-manager/android/src/main/java/community/revteltech/nfc/NfcManager.java:1080: error: cannot find symbol
          flag = PendingIntent.FLAG_MUTABLE;